// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dusopeuiirnecdyezggn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1c29wZXVpaXJuZWNkeWV6Z2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTIxMDYsImV4cCI6MjA3MDIyODEwNn0.znifpoyNDuMKaCrRdHmmQno6N17QI043SlBgj80Xz2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});